// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsHdzhX_-uurdC9J_p9b6qg2pR9OsGPzU',
    appId: '1:1016179852397:web:8b03d20b9b5834bfc0eb64',
    messagingSenderId: '1016179852397',
    projectId: 'bumo-32c08',
    authDomain: 'bumo-32c08.firebaseapp.com',
    storageBucket: 'bumo-32c08.firebasestorage.app',
    measurementId: 'G-62QJQB584V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqm7JFh1nq01zF2vmnC7u3v1-ArlN6f0',
    appId: '1:1016179852397:android:04b6240c788ae0fec0eb64',
    messagingSenderId: '1016179852397',
    projectId: 'bumo-32c08',
    storageBucket: 'bumo-32c08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXKAvT90XQoKwjCtVTgtyqUTSgeF-ag0',
    appId: '1:1016179852397:ios:d883d0cbeff4c69ac0eb64',
    messagingSenderId: '1016179852397',
    projectId: 'bumo-32c08',
    storageBucket: 'bumo-32c08.firebasestorage.app',
    iosBundleId: 'com.example.angkasCloneApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXKAvT90XQoKwjCtVTgtyqUTSgeF-ag0',
    appId: '1:1016179852397:ios:d883d0cbeff4c69ac0eb64',
    messagingSenderId: '1016179852397',
    projectId: 'bumo-32c08',
    storageBucket: 'bumo-32c08.firebasestorage.app',
    iosBundleId: 'com.example.angkasCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsHdzhX_-uurdC9J_p9b6qg2pR9OsGPzU',
    appId: '1:1016179852397:web:50e3c8e8ba1db6bbc0eb64',
    messagingSenderId: '1016179852397',
    projectId: 'bumo-32c08',
    authDomain: 'bumo-32c08.firebaseapp.com',
    storageBucket: 'bumo-32c08.firebasestorage.app',
    measurementId: 'G-L76DEQELPX',
  );
}
